services:
  scam-bank-gateway:
    image: microseversk/scam-bank-gateway:latest
    build: .
    container_name: scam-bank-gateway
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
      - EXEC_ENV=production
